### ISSUE TITLE
Move content of view upwards?

### ISSUE THREAD

**Issue by haleyngonadi** [ericcastro/ECStretchableHeaderView#4]
This is an awesome control, thank you for sharing. I'm wondering if it is possible to move the contents of the view upwards? 
1. Original View: http://i.imgur.com/TaDQoLV.jpg
2. View on Scroll: http://i.imgur.com/6ianfqq.jpg (please ignore the days, peak, I'd move it up later )
   3: What I want to achieve: http://i.imgur.com/vXUJoSt.png 

Is this possible? :)

**Comment by ericcastro** [comment]
Assuming you're using Auto-Layout (which I hope you are):

You need to add the necessary constraints to your UISegmentedControl. If it's supposed to have variable width, then attach it to the left, bottom and right edges of the header view. If it's not variable width, then add an horizontal center constraint, and attach it to the bottom edge of the header view.

**Comment by haleyngonadi** [comment]
Did the trick. Thank you so much!
