### ISSUE TITLE
Weird space before the scrollview?

### ISSUE THREAD

**Issue by haleyngonadi** [ericcastro/ECStretchableHeaderView#5]
Eric, It's me again. I'm using ECStretchableHeaderView with a scroll view and unlike with the tableview, there is a weird space before the headerview. It is the same size as the header above so it looks weird. I stretched the scrollview to the vert top, still the same issue.

Before Scroll: http://i.imgur.com/ljBboAi.png
After Scroll:  http://i.imgur.com/XSXRd1b.png

**Comment by ericcastro** [comment]
have you fixed this issue ? sorry I didn't see it before. if you havent solved it, please send me some code so I can review how you are doing this.
