### ISSUE TITLE
"viewForHeaderInSection" Not going up

### ISSUE THREAD

**Issue by nuwan5454** [ericcastro/ECStretchableHeaderView#6]
Hey,

First of all thanks for 'ECStretchableHeaderView'. Its amazing and really easy to use.

but if you add any section header with '-
 (UIView *)tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section' {
}
It will not go all the way to up. can you please give me an Idea how to add section headers with 'ECStretchableHeaderView'

**Comment by ericcastro** [comment]
Hi,

Please note that `viewForHeaderInSection` is a delegate method specific to UITableView, but ECStretchableHeaderView works at the UIScrollView level.

For this reason you are not meant to attach a header created with method `viewForHeaderInSection`. Instead, you must create your header view separately (programatically or in interface builder), and has to be at the same level in the view hierarchy as the UITableView. **It must not be a child view in your UITableView, this won't work**. The stretchable header view sits on top of it, not inside.

Please refer to the code example included to see how to achieve this.
